http:
  basePath: "/api/*"
  port: "8081"
  api:
    p-template-api:
      basePath: "/"
      host: ""
      port: ""
      path: ""  
      
#----Common Block---No change Needed----      
cloudhub:
  username: "![iz7//COkIEFNtURkhXV0krWKJGtWm8QU]"
  password: "![PkflFNbtA+Y+4XmwMZCrKw==]"
  
smtp:
  host: "mail.fatface.net"
  port: "465"
  user: "![iz7//COkIEFNtURkhXV0krWKJGtWm8QU]"
  password: "![PkflFNbtA+Y+4XmwMZCrKw==]"
  subject: "Fatface API Exception"
#----Common Block---No change Needed----

autodiscovery:
  id: ""
  flow: "x-template-api-main"

db:
 audit: 
  config:
   host: ""
   port: ""
   user: ""
   password: ""
   database: "" 

sftp:
  host: ""
  port: ""
  username: ""
  password: "" 
  
sqs:
  accessKey: ""
  secretKey: ""
  region: ""
  queue:
    target:
      inventory: ""
    url: 
      reprocessingQueue: ""
      targetQueueUrl: ""